# netlify.toml

[build]
  # Now, the command is just 'next build'.
  # Next.js will automatically export static files because of `output: 'export'` in next.config.js
  command = "next build"

  # The output directory for static exports is now 'out' (not '.next')
  publish = "out"

# This plugin is still essential for Netlify to understand Next.js projects,
# even if they are statically exported, as it sets up necessary redirects and headers.
[[plugins]]
  package = "@netlify/plugin-nextjs"

# This redirect is a good fallback for client-side routing on static exports.
# It ensures that if a direct URL (like /about) is accessed, index.html is served.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200